---
abstract: 'Utility methods and base class for manipulating Perl via PPI'
author:
  - 'Steffen Mueller C<smueller@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Differences: 0.4801
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: PPIx::EditorTools
name: PPIx-EditorTools
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::XSAccessor: 1.02
  PPI: 1.203
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.09
