---
abstract: ~
author:
  - 'Steffen Mueller C<smueller@cpan.org>'
  - 'Repackaged by Mark Grimes C<mgrimes@cpan.org>'
  - 'Ahmad M. Zawawi <ahmad.zawawi@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Find: 0
  File::Temp: 0
  Test::Differences: 0
  Test::More: 0.88
  Test::Most: 0
  Test::NoWarnings: 0.084
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PPIx-EditorTools
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::XSAccessor: 1.02
  File::Basename: 0
  File::Spec: 0
  PPI: 1.203
  PPI::Find: 0
  perl: 5.008005
resources:
  bugtracker: http://padre.perlide.org/trac/
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/PPIx-EditorTools/
version: 0.14
